refactor: Refactors earn page
leapdao/leapdao-website pull request #173
Opened 2020-06-13 11:17 UTC by agbilotia1998

Fixes #165 

- [x] Add a better introduction, make it appealing for developers to join us
- [x] Remove Resources page
- [ ]  Fix broken Glassfrog integration #158 #168 (For #158 - the roles fetched and filtered are appearing correctly(3 entries), please let me know if I missed anything here.
For #168 - I tested with yarn version `1.12.3` the build seems to be successful, please let me know if I missed anything here)
- [x] Remove Grant section #129

2020-06-13 11:18 UTC, agbilotia1998 commented
@Clearwood @johannbarbie please review. [Adding in case auto review request is not generated].

Apologies for the delay in the PR.

2020-06-17 18:54 UTC, agbilotia1998 commented
Hi @Clearwood, I updated the PR with the latest changes from master.

2020-06-17 18:55 UTC, Clearwood requested changes
The CTAs are missing. 
[here](https://hackmd.io/W4yA4jxYSka0VbdKPE-npg) you can have a look at the hackmd detailing our motivations for reworking the content. 
I am missing the drive to draw developers to us. I want everyone visiting this page to be stoked to work for LeapDAO.

2020-06-17 18:56 UTC, Clearwood commented on src/routes/earn.svelte
> +      earn with LeapDAO by completing a bounty, taking on a role, or applying
We don't have a grant program anymore. :)

2020-06-18 16:58 UTC, agbilotia1998 commented on src/routes/earn.svelte
> +      earn with LeapDAO by completing a bounty, taking on a role, or applying
Okay, I'll remove the grant program.

2020-06-18 17:51 UTC, agbilotia1998 commented
Hi @Clearwood, I've made changes to the content. Please review and let me know if it requires any other changes. Regarding the CTAs please let me know if anything else is required.

2020-07-02 10:02 UTC, agbilotia1998 commented
Hi @Clearwood please review this PR and let me know if any further changes are required in this. Thanks :) and sorry for the ping again!

2020-07-06 15:00 UTC, Clearwood commented
Sorry for the late reply, I am missing more information on who and what we are as a community at the core. @mwaa in case you have time would also enjoy your feedback.

2020-07-14 09:39 UTC, Clearwood commented
As per our bounty terms and missing updates I am going to challenge the bounty and close the Pull Request.

2020-07-14 09:39 UTC, closed without merging

2020-07-14 09:43 UTC, agbilotia1998 commented
I was waiting for review from @mwaa. Thanks anyways for giving me opportunity to work on this :)